# Generated by Django 5.2.6 on 2025-09-13 08:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
